version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Static Tests
          command: npm run test:static
      - run:
          name: Run Unit Tests
          command: npm run test:unit
      - run:
          name: Build for Production
          command: npm run build:prod

workflows:
  version: 2
  build:
    jobs:
      - build
